version: '2'

services:
  shadowsocks-manager:
    image: johnstevin/shadowsocks-manager-docker
    container_name: shadowsocks-manager
    ports:
      - "8388:8388"
      - "4001:4001"
      - "4002:4002"
      - "9001:9001"
      - "6001:6001"
      - "50000-50100:50000-50100"
    volumes: 
      - $PWD/supervisor:/etc/supervisor
      - $PWD/config:/etc/shadowsocks
      - $PWD/data:/root/.ssmgr
      - $PWD/code:/var/www/shadowsocks-manager
    links:
      - mysql
    restart: always
    privileged: true

  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    hostname: docker-mysql
#    networks:
#      - default
#      - domainA_default
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Chongqing
    restart: always
    privileged: true

#networks:
#  domainA_default:
#    external: true
