version: '2'

services:
  shadowsocks-manager:
    images: johnstevin/shadowsocks-manager-docker
    container_name: shadowsocks-manager
    ports:
      - "8388:8388"
      - "4001:4001"
      - "4002:4002"
      - "9001:9001"
      - "6001:6001"
      - "50000-50100:50000-50100"
    #volumes: 
      #- ./supervisor:/etc/supervisor
      #- ./config:/etc/shadowsocks
      #- ./data:/root/.ssmgr:rw 这里权限有问题，无法启动ssmgr
      #- ./code:/var/www/shadowsocks-manager
    links:
      - mysql
    restart: always

  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "3306:3306"
    hostname: docker-mysql
    volumes:
      - "./mysql/data:/var/lib/mysql:rw"  #todo权限的问题无法解决
    env_file: .env
    environment:
      TZ: Asia/Chongqing
      restart: always

